Peak news link
Technigo/technigo-project-news-site pull request #1
Opened 2024-08-22 12:08 UTC by zoe-lindqvist

https://peaknews-climbing-news-at-its-peak.netlify.app/

2024-08-27 09:36 UTC, JennieDalgren reviewed
Please add a working netlify link 😎

2024-09-06 21:49 UTC, JennieDalgren requested changes
Great job with this project!

You have worked really well with the responsive layouts, however you have some issues with your navbar causing some side scroll. This needs to be fixed before we can approved this project.
<img width="660" alt="image" src="https://github.com/user-attachments/assets/9eda2d36-9703-4a9a-8b3b-914077f5895a">

Good use of flex and grid. You code is clean and easy to follow and you have used comments in a good way.

Extra kudos for the nice ticker! It looks really news-site-y and proffesional!
Also nice that you managed to add a custom favicon, its all in the details 😉 

Keep up the good work!

2024-09-08 14:35 UTC, zoe-lindqvist commented
Thank you for the review Jenie :) 
I fixed the scrolling issue and it looks like working now.

2024-09-28 21:25 UTC, JennieDalgren approved these changes
⭐

2026-04-07 14:49 UTC, closed without merging